version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: mysql:8.0.17
    ports:
      - "3308:3306"
    env_file:
      - .env
    volumes:
      - node_db_data:/var/lib/mysql/data

volumes:
  node_db_data: {}
